### ISSUE TITLE
Forking or Branching from master or develop

### ISSUE THREAD

**Issue by jayantmukho** [su2code/su2code.github.io#2]
Hey! 

I made a fork from master and added a tutorial to go with my feature_SST_UQ pull request. I just noticed that the master and develop are out of sync (master is ahead because of additions for the IDS meeting).

Should I have forked from develop? And should I create a pull request into develop?

Cheers, 
Jayant

**Comment by economon** [comment]
Go with develop. The same structure is at play here, and the develop branch is the one that is checked out by Travis for regressions (some of the tutorials are executed for 1 iteration to make sure the configs are ok). Also, we make releases of this repo as well, so that we have a snapshot of the tutorial configs for the particular SU2 version.

We have to be a little more nimble with this repository, since only master is reflected on the web. Any changes we need to make that should be live happen in master right away. We will merge those changes back in to develop regularly.
